### ISSUE TITLE
ring.lru() maxsize behaves differently from functools.lru_cache() maxsize

### ISSUE THREAD

**Issue by dmhowcroft** [youknowone/ring#136]
In `functools.lru_cache()` you can specify `maxsize=None` if you want to allow the cache to grow indefinitely. 

If you try to do this with ring.lru(maxsize=None), however, you will run into a `TypeError` on line 117 of `lru_cache.py` when `cache_len()` is compared with `maxsize`, since the former is an integer and you have specified `None` for the latter.

Proposed fix:
Change the code in `lru_cache.py` to skip this bounds check if `maxsize is None`.

**Comment by youknowone** [comment]
This fix will be included in next release. Thanks to @xymz
