### ISSUE TITLE
Bug with lru and @staticmethod

### ISSUE THREAD

**Issue by VakarisZ** [youknowone/ring#145]
`@ring.lru()` doesn't retrieve the right value from methods with `@staticmethod`. 

[Code to reproduce.](https://gist.github.com/VakarisZ/4a66fabf12f2f77e0e01a067fb8181c8)

**Comment by youknowone** [comment]
Related fix: https://github.com/youknowone/wirerope/pull/4/files

**Comment by youknowone** [comment]
Thanks for the report. The bug fixed version 0.7.3 is now released. Will you test the new version please?

**Comment by VakarisZ** [comment]
Tested my dummy code, seems to work. Thanks for the quick fix!
