### ISSUE TITLE
Can`t aioredis Cache

### ISSUE THREAD

**Issue by chado13** [youknowone/ring#186]
i`m using 
python 3.7
aioredis 1.3.1

i used ring.aioredis to myfunction for data cache
like this,
@ring.aioredis(redis_connection, expire=2)

but i got typeerror

![image](https://user-images.githubusercontent.com/26504089/140265677-f7166455-f270-4192-a5e3-413e2641f805.png)

why occure this problem? i wonder how to solve this

**Comment by youknowone** [comment]
is this solved? I think aioredis 1 and aioredis 2 have different api
