### ISSUE TITLE
Change version constraint in setup.py

### ISSUE THREAD

**Issue by isaevmik** [youknowone/ring#188]
When adding ring package via poetry manager following error occurs:
```bash
Invalid constraint (functools32>=3.2.3-2>=0.1.0 ; python_version < "3.0") found in ring-0.9.1 dependencies, skipping
```
so installation breaks and ring could not be installed.

**Comment by youknowone** [comment]
Do you know how to fix it for poetry?

**Comment by youknowone** [comment]
try to fix: https://github.com/youknowone/ring/pull/190/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R21
