### ISSUE TITLE
Django(>v4) Support

### ISSUE THREAD

**Issue by wy-z** [youknowone/ring#198]
I noticed the latest version doesn't support Django>4. Could you clarify if this is permanent or if there are plans to reintroduce Django support in the future?

Thanks for your efforts and looking forward to your response.

**Comment by youknowone** [comment]
Hi. I didn't use Django for a long time. I don't think I have a proper opinion for it. What will be the best solution? I'd like to follow your suggestion.

**Comment by wy-z** [comment]
I also submitted a PR to fix support for Django v4 (reference https://github.com/youknowone/ring/pull/199) .
Please review it when convenient, much appreciated 🙏.

**Comment by wy-z** [comment]
Fix by https://github.com/youknowone/ring/pull/199
