### ISSUE TITLE
[BUG] `ring.func.dict` key collision bug

### ISSUE THREAD

**Issue by vazrupe** [youknowone/ring#31]
```
cache_dict = {}

@ring.func.dict(cache_dict)
def test(a);
    return a + 3

@ring.func.dict(cache_dict)
def test2(a):
    return a +4

print(test(3)) # 6
print(test2(3)) # 6 : bug
```

**Comment by Soonmok** [comment]
def test(a); 부분에 세미콜론 혹시 오타인가요 ?

**Comment by vazrupe** [comment]
넵 단순 오타입니다

**Comment by Soonmok** [comment]
제가 캐시에 대한것을 정확하게 몰라서 그런데 테스트 코드에는 test 함수랑 test2 함수가 같은 딕셔너리를 받고 있어서 딕셔너리에 같은 키의 값이 나오는것 같은데
그냥 다른 딕셔너리를 파라메터로 주면 해결되는 일 아닌가요 ?
아니면 다른 함수에 같은 딕셔너리를 파라메터로 줬다고 오류를 내야 하는건가요 ?

**Comment by Soonmok** [comment]
제가 캐시에 대한것을 정확하게 몰라서 그런데 테스트 코드에는 test 함수랑 test2 함수가 같은 딕셔너리를 받고 있어서 딕셔너리에 같은 키의 값이 나오는것 같은데
그냥 다른 딕셔너리를 파라메터로 주면 해결되는 일 아닌가요 ?
아니면 다른 함수에 같은 딕셔너리를 파라메터로 줬다고 오류를 내야 하는건가요 ?

**Comment by youknowone** [comment]
지금은 그래서 다른 딕셔너리를 주거나 다른 key prefix를 지정해야하는데요.
memcache나 redis 등의 db를 저장소로 쓸때는 기본값으로 두어도 알아서 key prefix를 바꾸기 때문에 그런 문제가 생기지 않습니다.

dict의 동작을 memcache, redis와 일치하도록 변경해야 하는 이슈로 보시면 됩니다.
