### ISSUE TITLE
[WRANING] pytest it is not a function

### ISSUE THREAD

**Issue by jowoojun** [youknowone/ring#39]
import ring

cache_dict = {}

@ring.func.dict(cache_dict)
def test(a):
    return a + 3

@ring.func.dict(cache_dict)
def test2(a):
    return a +4

print(test(3)) # 6
print(test2(3)) # 6 : bug

![image](https://user-images.githubusercontent.com/22931457/32493903-ea625544-c402-11e7-9ef5-3da3e1ff9843.png)

**Comment by youknowone** [comment]
Hello, ring project doesn't have `tests/test_dict.py` in the repository. The warnings seems to be generated from your local files.

The issue itself is reported in #31.

**Comment by yunitto** [comment]
pytest 에서는 ```test_``` 로 시작하는 함수를 자동으로 collect합니다. 작성하신 test, test2 함수의 경우는 이름은 test로 시작하는 함수지만 ring decorator로 감싸져 있기 때문에 ring object가 됩니다. ```cannot collect 'test' because it is not a function.``` 은 (확실하진 않지만)아마 그런 맥락에서 나온 warning 인 것 같습니다. warning을 없애려면 test/test2의 이름이 test로 시작하지 않게 바꾸거나, ring decorator로 감싸지 않은 새로운 테스트 함수 안에서 test/test2를 선언하면 됩니다.
