### ISSUE TITLE
PickleCoder behaves differently depending on version

### ISSUE THREAD

**Issue by jowoojun** [youknowone/ring#51]
![image](https://user-images.githubusercontent.com/22931457/32942110-539d4d5a-cbcb-11e7-8d8c-a12dfe33b69b.png)
![image](https://user-images.githubusercontent.com/22931457/32942147-76e21386-cbcb-11e7-8d80-32a1e101d20c.png)
pull request에 올려둔 https://github.com/youknowone/ring/pull/50 에서 위와 같은 에러가 발생하는데 어떻게 버전에 따라 다르게 써줘야 하는지 모르겠습니다...

**Comment by youknowone** [comment]
py2와 py3에서 pickle의 결과가 다르기 때문인데요.
테스트의 목적은 결과가 pickle된 결과와 같은지를 테스트하는 것이지 바이너리의 값을 꼭 테스트할 필요는 없습니다.

그냥 assert pickle.dumps(1) == ring.coder.picker.encode(1) 이어도 될것 같아요.

**Comment by jowoojun** [comment]
넵! 수정해서 다시 올리겠습니다!

**Comment by youknowone** [comment]
#50
