### ISSUE TITLE
[bug] 'RedisConnection' object has no attribute

### ISSUE THREAD

**Issue by jowoojun** [youknowone/ring#52]
![image](https://user-images.githubusercontent.com/22931457/32977398-fa54879a-cc6f-11e7-85a1-6da009b221cd.png)
![image](https://user-images.githubusercontent.com/22931457/32977403-0d40ab04-cc70-11e7-9381-6d56c6e5902a.png)
PickleCoder쪽은 pyenv 를 통해 python2와 python3에서 pytest는 에러가 없는데 대신에 test_common과 test_complicated_key에서 에러가 발생했는데 제가 한번도 안 건드린 곳이라서.. 이유를 잘 모르겠습니다...

**Comment by youknowone** [comment]
PR에 관련된 질문은 PR에 코멘트로 남겨주시면 한번에 보기 좋습니다.
[bug]는 보통 프로젝트의 버그 리포트를 의미한다고 생각됩니다. 직접 작성하신 코드에 대한 질문은 따로 구분되게 올려주시면 좋겠습니다.

**Comment by youknowone** [comment]
#50
