### ISSUE TITLE
Follow up aioredis api breaking change

### ISSUE THREAD

**Issue by youknowone** [youknowone/ring#54]
- Short term fix: Specify last working aioredis version in setup.py
- Long term fix: Migrate to new aioredis code and specify least version to guarantee not to be broken

**Comment by yunitto** [comment]
For Python 3.3, 3.4 support use aioredis v0.3. (https://github.com/aio-libs/aioredis#id2)

**Comment by youknowone** [comment]
I think 3.3 and 3.4 are already very old versions. We can drop them from official supports.
(Users still can migration current aioredis implementation to future versions if they really need aioredis support before 3.4)

**Comment by youknowone** [comment]
Fixed in #56
